
class Window:
    WIDTH = 600
    HEIGHT = 600
    SIZE = (WIDTH, HEIGHT)
    FPS = 60
    TITLE = "ChessBee Engine"
    SQUARE_SIZE = 60
    HIGHLIGHT_SIZE = SQUARE_SIZE/3
    BOARD_XMIN = (WIDTH - (8*SQUARE_SIZE))/2
    BOARD_YMIN = (HEIGHT - (8*SQUARE_SIZE))/2

